### ISSUE TITLE
Create A Sheet And Endpoint For Rule Book

### ISSUE THREAD

**Issue by thealphadollar** [tsg-iitkgp/Gymkhana-BackServer#6]
We need a sheet with the following fields:
- Event Name
- Date
- Cup
- Rule Book

In the same sheet, have two spreadsheets one for GC and other for Open IIT.

This will be reflected on the frontend as well.

**Comment by rakaar** [comment]
#7 is the same issue @thealphadollar  ?

**Comment by thealphadollar** [comment]
same as #7
