### ISSUE TITLE
Add endpoint and sheet for rulebook

### ISSUE THREAD

**Issue by thealphadollar** [tsg-iitkgp/Gymkhana-BackServer#7]
As per https://github.com/tsg-iitkgp/tsg/pull/35 an endpoint should be added to the backend which would server files from a sheet which needs to be created with the following columns:

- Event
- Cup
- Date
- Link To Rulebook

@mukul-mehta @rakaar Please take note.

**Comment by rakaar** [comment]
@mukul-mehta  Create the sheet and put the link here

**Comment by mukul-mehta** [comment]
https://docs.google.com/spreadsheets/d/1OQylznjwOY4GntvooHW1MLjt_AgGguRoG6rU20xWVic/edit?usp=sharing

**Comment by thealphadollar** [comment]
@rakaar please use the above provided sheet.

**Comment by thealphadollar** [comment]
fixed via #10
